data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"
  plk_path: "data/plk/"

preprocessing:
  test_size: 0.2
  random_state: 42
  scale: true

models:
  logistic_regression:
    C: 10.0
  random_forest:
    min_samples_split: 10
    n_estimators: 200
    max_depth: 10
  lightgbm:
    num_leaves: 31
    learning_rate: 0.01
    n_estimators: 200
  xgboost:
    learning_rate: 0.01
    max_depth: 5
    n_estimators: 500
    subsample: 0.8